token: "TOKEN_HERE"
themeColor:
    red: 235
    green: 110
    blue: 52
openAI:
    - name: "grammar"
        endpoint: "https://api.openai.com/v1/responses"
        apikey: "xxxxx"
mongoDB:
    uri: "URI_HERE" #Example: mongodb://user:password@127.0.0.1:27017/
    database: "foxbot"
apiKeys:
    giphy: "KEY_HERE"
zipline:
    enabled: true
    endpoint: https://share.nat.gg
    token: "INSERT_TOKEN_HERE"
channels:
    foodStash: 0
    instructionChannel: 0
    rulesChannel: 0
    rolesChannel: 0
    wakeup1: 0
    wakeup2: 0
    dailyFox: 0
party:
    enabled: false
    newPartyChannel: 0
    partyCategory: 0
    blacklistedNames:
        - fuck
        - nigger
socialCredits:
    minVoiceTime: 5 #Minutes
    rewardInterval: 60 #Minutes
    useAllChannels: false
    channels:
        - 0
general:
    inviteCountToRole: 10
emojies:
    upvote:
        name: "upvote"
        id: 0
        animated: false
    downvote:
        name: "downvote"
        id: 0
        animated: false
    info:
        name: "info"
        id: 0
        animated: false
    usage:
        name: "usage"
        id: 0
        animated: false
    error:
        name: "error"
        id: 0
        animated: false